name: Build Hugo & Deploy to site-deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blog repo
        uses: actions/checkout@v3

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --baseURL "/blog/"

      - name: Push to site-deploy repo (blog/)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone --branch gh-pages https://x-access-token:${{ secrets.GH_PAT }}@github.com/anmol-thapa/site-deploy.git deploy
          rm -rf deploy/blog
          mkdir -p deploy/blog
          cp -r public/* deploy/blog/
          cd deploy
          git add .
          git commit -m "Update blog via Hugo build"
          git push
